<?php

namespace Mounir\BlogBundle\Repository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends \Doctrine\ORM\EntityRepository
{
  public function getListCategorie()
  {

    $sql  ="SELECT  COUNT(DISTINCT a.id) as nbrarticle, c.nom as nameCat FROM MounirBlogBundle:Article a JOIN a.categorie c  group by a.categorie";

    $query = $this->_em->createQuery($sql);

    return $query->getResult();
  }
}
