fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

Mounir_blog:
    resource: "@MounirBlogBundle/Resources/config/routing.yml"

elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"
